project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: false
    watch-inputs: false  # Add this
    navigate: false      # Add this
    
website:
  title: "Notebooks"
  site-url: "https://notes.livingphysics.org"
  description: "Notes from the living physics Lab"
  navbar:
    left:
      - href: index.qmd
        text: Notes Home
      - about.qmd
      - tech.qmd
      - builds.qmd
      - concepts.qmd
      - icon: globe
        text: Main Site
        href: https://livingphysics.org
      - icon: rss
        text: RSS Feed
        href: index.xml
format:
  html:
    theme: darkly
    css: ./styles.css
    toc: true
feed:
  type: rss
  image-height: 60
  image-width: 60
execute:
  freeze: false
editor:
  render-on-save: true