project:
  type: website
  output-dir: docs

website:
  title: "Notebooks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tech.qmd
      - builds.qmd
      - icon: globe
        href: https://livingphysics.org

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto