project:
  type: website
  output-dir: docs

website:
  title: "Notebooks"
  site-url: ""
  description: "Notes from the living physics Lab"
  navbar:
    left:
      - href: index.qmd
        text: Notes Home
      - about.qmd
      - tech.qmd
      - builds.qmd
      - concepts.qmd
      - icon: globe
        text: Main Site
        href: https://livingphysics.org
      - icon: rss
        href: index.xml
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
feed:
  type: rss
execute:
  freeze: auto